// lib/appbuilder/artifacts.ts — real deploy config files from wizard choices
import type { AppProject } from "./types";

export function buildGithubActionsYaml(project: AppProject): string {
  const onPush = project.cicd.triggers.includes("push-main");
  const onPr = project.cicd.triggers.includes("pull-request");
  const frontend = project.stack.frontend;
  const buildCmd =
    frontend === "angular"
      ? "npm ci && npm run build"
      : "npm ci && npm run build";

  return `name: CI/CD

on:
${onPush ? `  push:\n    branches: [main]\n` : ""}${onPr ? `  pull_request:\n    branches: [main]\n` : ""}${
    project.cicd.triggers.includes("manual")
      ? `  workflow_dispatch:\n`
      : ""
  }
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install & Build
        run: ${buildCmd}
${
  project.cicd.advanced.includes("tests")
    ? `
      - name: Test
        run: npm test --if-present
`
    : ""
}${
  project.cicd.advanced.includes("sast")
    ? `
      - name: Lint
        run: npm run lint --if-present
`
    : ""
}${
  project.cicd.advanced.includes("docker")
    ? `
      - name: Build Docker image
        run: docker build -t ${project.repository.repoName}:$GITHUB_SHA .
`
    : ""
}
      - name: Deploy to ${project.cicd.targetCloud} (${project.cicd.region})
        run: |
          echo "Deploy ${project.name} via ${project.cicd.service}"
          echo "Environments: ${project.cicd.environments.join(", ")}"
`;
}

export function buildDockerfile(project: AppProject): string {
  return `# Generated by AppBuilder AI for ${project.name}
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/out /usr/share/nginx/html
# For Next.js standalone, swap to node runner; static export uses nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`;
}

export function buildReadme(project: AppProject): string {
  return `# ${project.name}

Generated by **AppBuilder AI**.

## Stack
- Frontend: ${project.stack.frontend}
- Backend: ${project.stack.backend}
- Database: ${project.stack.database}
- Cloud: ${project.deploy.cloud} / ${project.deploy.compute}
- Architecture: ${project.deploy.architecture}

## Idea
${project.idea}

## Features
${project.features.join(", ")}

## Local preview
Open the HTML files in \`/site\` (index.html first).

## CI/CD
See \`.github/workflows/ci-cd.yml\` and \`Dockerfile\`.
`;
}
